insert into USERS (`NAME`, `USERNAME`, `PASSWORD`, `ACTIVE`)
VALUES ('ADMIN', 'admin', '$2a$10$B042kZ1aAdyef3r5ITWHN.yRT3l6YwuuO2PpupxuP/2ylbZmIUUnK', 1);
insert into USERS (`NAME`, `USERNAME`, `PASSWORD`, `ACTIVE`)
VALUES ('Рога и Копыта', 'roga', '$2a$10$B042kZ1aAdyef3r5ITWHN.yRT3l6YwuuO2PpupxuP/2ylbZmIUUnK', 1);
insert into USERS (`NAME`, `USERNAME`, `PASSWORD`, `ACTIVE`)
VALUES ('Кошкин дом', 'cat', '$2a$10$B042kZ1aAdyef3r5ITWHN.yRT3l6YwuuO2PpupxuP/2ylbZmIUUnK', 1);

INSERT INTO ROLE (`ROLE`) VALUES ('ADMIN');
INSERT INTO ROLE (`ROLE`) VALUES ('USER');

INSERT INTO USER_ROLE (`USER_ID`, `ROLE_ID`) VALUES (1,1);
INSERT INTO USER_ROLE (`USER_ID`, `ROLE_ID`) VALUES (2,2);
INSERT INTO USER_ROLE (`USER_ID`, `ROLE_ID`) VALUES (3,2);

insert into DOCUMENT (`NAME`,`NUMBER`, `CREATOR_ID`, `SECOND_SIDE_ID`)
VALUES ('Договор','РК/01', 2, 3);
insert into DOCUMENT (`NAME`,`NUMBER`, `CREATOR_ID`, `SECOND_SIDE_ID`)
VALUES ('Соглашение','РК/01-С1', 3, 2);
insert into DOCUMENT (`NAME`,`NUMBER`, `CREATOR_ID`, `SECOND_SIDE_ID`)
VALUES ('Спецификация','РК/01-01', 2, 3);
insert into DOCUMENT (`NAME`,`NUMBER`, `CREATOR_ID`, `SECOND_SIDE_ID`)
VALUES ('Спецификация','РК/01-02', 3, 2);

insert into SIGNATURE (`USER_ID`,`DOCUMENT_ID`, `SIGNATURE`)
VALUES (2,1, TRUE);
insert into SIGNATURE (`USER_ID`,`DOCUMENT_ID`, `SIGNATURE`)
VALUES (3,1, TRUE);
insert into SIGNATURE (`USER_ID`,`DOCUMENT_ID`, `SIGNATURE`)
VALUES (2,2, TRUE);
insert into SIGNATURE (`USER_ID`,`DOCUMENT_ID`, `SIGNATURE`)
VALUES (3,2, FALSE);
insert into SIGNATURE (`USER_ID`,`DOCUMENT_ID`, `SIGNATURE`)
VALUES (2,3, FALSE);
insert into SIGNATURE (`USER_ID`,`DOCUMENT_ID`, `SIGNATURE`)
VALUES (3,3, FALSE);
insert into SIGNATURE (`USER_ID`,`DOCUMENT_ID`, `SIGNATURE`)
VALUES (2,4, FALSE);
insert into SIGNATURE (`USER_ID`,`DOCUMENT_ID`, `SIGNATURE`)
VALUES (3,4, TRUE);




